# Name of the workflow
name: Pre-Release

# Run on every push to main
on:
  push:
    branches:
      - "dev"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  image-name:
    runs-on: ubuntu-latest
    steps:
      - name: Parse short sha
        id: short-sha
        run: |
          echo "Hello world"
