# Name of the workflow
name: Pre-Release

# Run on every push to main
on:
  push:
    branches:
      - "dev"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  image-name:
    runs-on: ubuntu-latest
    steps:
      - name: Set filename
        id: short-sha
        run: |
          echo "GET FILENAME"
          FILE_NAME="${REPOSITORY_NAME}.zip"
          echo $FILE_NAME >> $GITHUB_OUTPUT
          echo "$FILE_NAME"
          echo $FILE_NAME
          echo $GITHUB_OUTPUT
