# Name of the workflow
name: Pre-Release

# Run on every push to main
on:
  push:
    branches:
      - "release"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: get-name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: "Install dependences"
        run: |
          echo "Install npm dependences"
          npm install
      - name: "Build js"
        run: |
          echo "Building gulp assets!"
          gulp build
      - name: "Create zip file"
        run: |
          NAME="deployment1"
          REPOSITORY=${{ github.event.repository.name }}
          echo "! $REPOSITORY"
          echo " !! ${{ env.REPO_NAME }} "
        #     FILENAME="${REPOSITORY}.zip"
       #      echo "$FILENAME";
      #       zip -r "$FILENAME" assets gracias.html index.html send_email.php
     # - uses: "marvinpinto/action-automatic-releases@latest"
       #  with:
         #  repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # automatic_release_tag: "latest"
          # prerelease: true
          # title: "Development Build"
          # files: |
          #   *.zip
