# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: "Set filename"
        run: |
          if [[ -z "$VERSION" ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            VERSION="${VERSION#v}"
          fi
          echo "ℹ︎ Version: $VERSION"
          REPOSITORY_NAME=${{ github.event.repository.name }}
          FILE_NAME="${REPOSITORY_NAME}-${VERSION}.zip"
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
      - name: "Install dependences"
        run: |
          echo "Install npm dependences"
          npm install
      - name: "Build js"
        run: |
          echo "Building gulp assets!"
          gulp build
      - name: "Create zip file"
        run: |
          echo "Creating Zip file!"
          zip -r "${{ env.FILE_NAME }}" assets gracias.html index.html send_email.php
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          #automatic_release_tag: "latest" Uncomment to put your custom tag
          prerelease: false
          #title: "Development Build" Uncomment to put your custom title
          files: |
            ${{ env.FILE_NAME }}