# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: "Install dependences"
        run: |
          echo "Install npm dependences"
          npm install
      - name: "Build js"
        run: |
          echo "Building gulp assets!"
          gulp build
      - name: "Create zip file"
        run: |
            zip -r deployment.zip assets gracias.html index.html send_mail.php
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          #automatic_release_tag: "latest"
          prerelease: false
          #title: "Development Build" Uncomment to put your custom tag
          files: |
            deployment.zip